name: ml-custom
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - et_xmlfile=1.1.0
  - libffi=3.4.4
  - openpyxl=3.1.5
  - openssl=3.0.16
  - pip=25.0
  - python=3.11.11
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - appdirs==1.4.4
      - asgiref==3.8.1
      - astroid==3.3.8
      - asttokens==3.0.0
      - astunparse==1.6.3
      - attrs==25.1.0
      - azure-ai-ml==1.27.0
      - azure-common==1.1.28
      - azure-core==1.34.0
      - azure-core-tracing-opentelemetry==1.0.0b12
      - azure-identity==1.22.0
      - azure-mgmt-core==1.5.0
      - azure-monitor-opentelemetry==1.6.8
      - azure-monitor-opentelemetry-exporter==1.0.0b36
      - azure-storage-blob==12.25.1
      - azure-storage-file-datalake==12.20.0
      - azure-storage-file-share==12.21.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.0
      - black==25.1.0
      - bleach==6.2.0
      - cachetools==5.5.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - check-shapes==1.1.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - cryptography==44.0.3
      - cycler==0.12.1
      - dataclasses==0.6
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.9
      - dm-tree==0.1.9
      - dropstackframe==0.1.1
      - empyrical==0.5.5
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fixedint==0.1.6
      - flatbuffers==25.1.24
      - fonttools==4.55.8
      - frozendict==2.4.6
      - fsspec==2025.3.2
      - gast==0.6.0
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - gpflow==2.9.2
      - grpcio==1.70.0
      - h5py==3.12.1
      - html5lib==1.1
      - idna==3.10
      - importlib-metadata==8.6.1
      - inflection==0.5.1
      - ipykernel==6.29.5
      - ipython==8.32.0
      - ipython-genutils==0.2.0
      - isodate==0.7.2
      - isort==6.0.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keras==3.8.0
      - keras-preprocessing==1.1.2
      - keras-tuner==1.4.7
      - kiwisolver==1.4.8
      - kt-legacy==1.0.5
      - lark==1.2.2
      - lazy-object-proxy==1.10.0
      - libclang==18.1.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.3
      - ml-dtypes==0.4.1
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msal==1.32.3
      - msal-extensions==1.3.1
      - msrest==0.7.1
      - multipledispatch==1.0.0
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.0.2
      - oauthlib==3.2.2
      - opentelemetry-api==1.31.1
      - opentelemetry-instrumentation==0.52b1
      - opentelemetry-instrumentation-asgi==0.52b1
      - opentelemetry-instrumentation-dbapi==0.52b1
      - opentelemetry-instrumentation-django==0.52b1
      - opentelemetry-instrumentation-fastapi==0.52b1
      - opentelemetry-instrumentation-flask==0.52b1
      - opentelemetry-instrumentation-psycopg2==0.52b1
      - opentelemetry-instrumentation-requests==0.52b1
      - opentelemetry-instrumentation-urllib==0.52b1
      - opentelemetry-instrumentation-urllib3==0.52b1
      - opentelemetry-instrumentation-wsgi==0.52b1
      - opentelemetry-resource-detector-azure==0.1.5
      - opentelemetry-sdk==1.31.1
      - opentelemetry-semantic-conventions==0.52b1
      - opentelemetry-util-http==0.52b1
      - opt-einsum==3.4.0
      - optree==0.14.0
      - packaging==24.2
      - pandas==2.2.3
      - pandas-datareader==0.10.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - patsy==1.0.1
      - peewee==3.17.8
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.1.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydash==8.0.5
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pylint==3.3.4
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - quandl==3.7.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rpds-py==0.24.0
      - rsa==4.9
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - six==1.17.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - strictyaml==1.7.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - termcolor==2.5.0
      - tf-keras==2.18.0
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.7.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - yfinance==0.2.52
      - zipp==3.21.0
